### PR TITLE
VHF contest improvement suggestions

### PR DESCRIPTION
**Pull request by pleaswaite**

### CODE REVIEW

**Comment by clumens** [comment]
Here's a list that is categorized and prioritized, and I believe takes into account your suggestions above and most of the critical stuff from email:

HARDWARE                                                    | PRIORITY | COST
------------------------------------------------------------|----------|-----------
voice keyers for radios without                             | HIGH     | MEDIUM
222 transverter and beam                                    | HIGH     | HIGH
bandpass filter or coax stub filter for 6m                  | MEDIUM   | MEDIUM
bandpass filter or coax stub filter for 2m                  | MEDIUM   | MEDIUM
FM mobile and antennas for 2m/70cm                          | MEDIUM   | MEDIUM
150W 2m amp, w/ preamp, mast-mounted                        | LOW      | HIGH
100W 70cm amp, w/ preamp, mast-mounted                      | LOW      | HIGH
bandpass filter or coax stub filter for 1.25m               | LOW      | MEDIUM
bandpass filter or coax stub filter for 70cm                | LOW      | MEDIUM

OPERATIONS                                                  | PRIORITY | COST
------------------------------------------------------------|----------|-----------
have someone who can do CW                                  | HIGH     |
network-aware logging                                       | MEDIUM   |
get information on rovers                                   | MEDIUM   |
follow rovers on APRS                                       | MEDIUM   |
join local VHF mailing lists, etc.                          | MEDIUM   |
schedule with other locals                                  | LOW      |
precalculated antenna bearings for likely contacts          | LOW      |
consider meteor scatter, jt65, etc.                         | LOW      |

STATION                                                     | PRIORITY | COST
------------------------------------------------------------|----------|-----------
get beams up higher, or operate from a better location      | HIGH     | UNKNOWN
IC-7000 on 2m/70cm, FT-857 on 6m                            | HIGH     | LOW
aluminum plates under masts to protect deck                 | HIGH     | LOW
compass roses at masts                                      | MEDIUM   | LOW
ferrites for feed lines, control lines, etc.                | LOW      | LOW

**Comment by pleaswaite** [comment]
Quick changes to that would be that I have the 2m mobile now, so we'd need an antenna for it and then a rig/antenna for 70cm FM. If we've got mast space for more beams, http://www.wa5vjb.com/yagi-pdf/cheapyagi.pdf seems like a quick/cheap way to throw together yagis for the FM rigs, or we can just use j-poles or similar.

We probably want TWO CW operators, but if it's just one we can play hot-seat when it's needed. 

If we've got more than 2 ops, discrete rigs for 2 and 70 would be great. With 3 ops we'd have 1 on 6, 1 on 2 and 1 on 1.25/70.

**Comment by clumens** [comment]
Okay, I'll make some edits.  70cm FM seems pretty low priority to me - lower than 2m I think.  Having two CW ops might be better material for an operations manual.  I was thinking we wouldn't have a full-time dedicated CW operator, just someone who could switch over to it as-needed.  The operators-to-radio thing sounds like operations manual material too.  We could discuss the merits of a dedicated 70cm operator vs. someone subbing in and doing intel (watching spots, talking to rovers, etc).

**Comment by pleaswaite** [comment]
Alright, agreed on all points. I made one FM 440 contact at the ARRL Jan VHF+ contest, and only a handful overall. A better operating location may increase this, as well as increase 220 beyond what one person can do. If you look at the hamcow 2009 Jan VHF contest site, they had separate operating positions for 6, 2, 1.25, 70, and the "all others" so clearly with a bigger gun station up high we'd be busier on those bands. I think it may be worth adding a low-priority/high cost item for a dedicated 70cm station to the list. It's not like we're going to have these all up and running by September. The other points can go into our operating manual.

**Comment by clumens** [comment]
Updated.  I'll extract this from the comment, push, and close.  I was going to push our log for the contest anyway now that my cabrillo support is getting solid.

**Pull request closed without merging**
